//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebside.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public System.Guid ItemId { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string itemCode { get; set; }
        public string itemName { get; set; }
        public string Description { get; set; }
        public string imagePath { get; set; }
        public Nullable<int> itemPrice { get; set; }
    }
}
